---
- name: Test
  hosts: CSR1kv
  gather_facts: false
  connection: local

  tasks:
   - name: Show version
     ios_command:
       commands:
         - show version
     register: result_version
   - name: Print result
     debug: var=result_version
   - name: Show interfaces
     ios_command:
       commands:
         - show interfaces
     register: result_interfaces
   - name: Print result
     debug: var=result_interfaces

   - name: Clear counters
     ios_command:
      commands:
        - command: 'clear counters GigabitEthernet0/0'
          prompt: 'Clear "show interface" counters on this interface \[confirm\]'
          answer: 'y'
    